title: 광장 연습 / 녹음실
email: pilotedeguerre@gmail.com
description: 백남준아트센터 7월 12일 설치 시작. 전시 - 손에 폰잡고 - 광장연습(Phone-in-hand - Comforting Gesture)의 목소리 녹음용 사이트. mobile(특히, iOS)에서는 작동하지 않을 수 있습니다.
url: "/njp-jekyll-bulma"
production_url : https://applecargo.github.io/njp-jekyll-bulma
BASE_PATH : https://applecargo.github.io/njp-jekyll-bulma
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
name: phone-in-hand
markdown: kramdown
port: 5000
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
include: ["_pages"]
